In [64]:
import pandas as pd
import numpy as np

import os
import scipy
from numpy.linalg import svd
import sklearn

In [2]:
os.getcwd()

'C:\\Users\\admin\\Desktop\\yes24'

In [3]:
data = pd.read_csv('C:/Users/admin/Desktop/yes24/capstone_data.csv',encoding='utf-8',error_bad_lines=False)

In [78]:
data.shape

(15607311, 9)

In [28]:
data_half = data[:10000]

In [29]:
cross_data1 = pd.crosstab(data_half.account_id,data_half.product_id)

In [41]:
cross_data1[cross_data1.iloc[:,4]!=0]

product_id,2423,14449,19658,21936,22746,24834,25454,31081,32351,35404,...,12191059,12192764,12252582,12281622,12292464,12320639,12397511,12398557,12416187,12425581
account_id,,,,,,,,,,,,,,,,,,,,,
604276,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
640435,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
651477,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
744918,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
952461,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1086786,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1197450,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1215856,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1822802,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3213790,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3527813,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4022982,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4793106,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5336487,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5488282,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5673055,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5771639,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6304454,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6401244,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8640743,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9062744,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9442289,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11209774,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11889993,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12270388,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12600973,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12662464,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12774082,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12921172,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13126035,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13230478,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14485496,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14846289,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15225855,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15460169,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
cross_data1

product_id,2423,14449,19658,21936,22746,24834,25454,31081,32351,35404,...,12191059,12192764,12252582,12281622,12292464,12320639,12397511,12398557,12416187,12425581
account_id,,,,,,,,,,,,,,,,,,,,,
101634,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101935,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
102048,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
104022,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
107360,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16940624,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16942184,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16943591,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16958606,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16961421,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [56]:
U, S, VT = svd(cross_data1,full_matrices=False)

In [62]:
print(U)
print(U.shape)

[[ 3.05040494e-20 -2.11516444e-18 -1.35026229e-20 ... -1.29409477e-18
   3.01861634e-19 -5.57572489e-18]
 [ 1.14604104e-18  1.30637908e-20  4.49055193e-22 ... -7.87249676e-23
  -2.24451306e-20  1.26199777e-17]
 [ 8.93736377e-27 -1.18274224e-24 -1.83660200e-25 ... -1.53375427e-26
   6.99928448e-21 -1.81490484e-16]
 ...
 [-6.08510517e-10  1.23127096e-07 -7.92552333e-08 ...  5.54441172e-06
  -1.02226424e-17  7.49528831e-19]
 [-2.71905284e-04  3.42642312e-02  1.51866644e-03 ...  7.02164157e-09
   1.18634919e-19 -8.60188063e-21]
 [ 1.72211393e-24 -2.21738501e-22 -1.00069728e-23 ...  1.42213002e-24
  -1.86815211e-37 -4.04820167e-38]]
(9310, 572)

In [63]:
print(S)
print(S.shape)

[32.78113118 29.15782777 27.45783198 21.40444296 20.00046041 19.21006404
 16.063884   15.4611476  14.74599282 14.42009804 13.41728949 13.31736595
 12.44341294 11.45541572 11.31096718 10.72434113 10.34471631 10.11269883
 10.00018494  9.89949494  9.38049795  9.27910626  9.11043358  8.93512638
  8.83328059  8.77496439  8.77488034  8.60251448  8.54400375  8.06268071
  8.06225775  8.04844609  7.99620881  7.93725393  7.68114575  7.54983444
  7.52895717  7.48331477  7.14142843  7.14074003  7.          6.99979645
  6.92820323  6.8556546   6.78232998  6.78232998  6.63324958  6.63324958
  6.55743852  6.55743852  6.48276928  6.4807407   6.40387738  6.32455532
  6.24338475  6.164414    5.91863796  5.85202625  5.75416663  5.74456265
  5.74384851  5.56658283  5.56624888  5.38516481  5.38516481  5.3780328
  5.29150262  5.29041655  5.19615242  5.19615242  5.19615242  5.19615242
  5.09901951  5.00453405  4.9932829   4.95288291  4.89897949  4.79583152
  4.79583152  4.69041576  4.69041576  4.69041576  4.4720013   4.47181592
  4.37299733  4.35889894  4.35889894  4.35889894  4.35889894  4.35889894
  4.35889894  4.24264069  4.24264069  4.24264069  4.24264069  4.24264069
  4.2135245   4.12310563  4.05804767  4.          4.          4.
  4.          4.          4.          3.87298335  3.87298335  3.87298335
  3.87298335  3.87298335  3.87282858  3.87140054  3.85870009  3.74165739
  3.74165739  3.74165739  3.74165739  3.74165739  3.74074562  3.62074194
  3.60555128  3.60555128  3.60555128  3.52338098  3.49800914  3.46410162
  3.46410162  3.46410162  3.46410162  3.46410162  3.46410162  3.46410162
  3.43284586  3.31662479  3.31662479  3.31662479  3.31662479  3.31662479
  3.31662479  3.31662479  3.31662479  3.31571477  3.2980137   3.18783275
  3.16227766  3.16227766  3.16227766  3.16227766  3.16227766  3.16227766
  3.16227766  3.16227766  3.16227766  3.16227766  3.16134736  3.15995635
  3.0966402   3.09609212  3.          3.          3.          3.
  3.          3.          3.          3.          3.          3.
  3.          2.99910975  2.82842712  2.82842712  2.82842712  2.82842712
  2.82842712  2.82842712  2.82842712  2.82842712  2.78638332  2.67260729
  2.64575131  2.64575131  2.64575131  2.64575131  2.64575131  2.64575131
  2.64575131  2.64575131  2.64575131  2.5975732   2.44948974  2.44948974
  2.44948974  2.44948974  2.44948974  2.44948974  2.44948974  2.44948974
  2.44948974  2.44948974  2.44948974  2.44948974  2.44948974  2.44948974
  2.44948974  2.44948974  2.44948974  2.44948974  2.44948974  2.44948974
  2.37023923  2.23606798  2.23606798  2.23606798  2.23606798  2.23606798
  2.23606798  2.23606798  2.23606798  2.23606798  2.23606798  2.23606798
  2.23606798  2.23606798  2.23606798  2.23606798  2.23606798  2.23606798
  2.23606798  2.23606798  2.23606798  2.23606798  2.23606798  2.23606798
  2.23606798  2.23557469  2.23546808  2.23457358  2.23371308  2.22901305
  2.07431329  2.          2.          2.          2.          2.
  2.          2.          2.          2.          2.          2.
  2.          2.          2.          2.          2.          2.
  2.          2.          2.          2.          2.          2.
  2.          2.          2.          1.99976574  1.99587739  1.99341476
  1.97236603  1.95901055  1.83901224  1.73205081  1.73205081  1.73205081
  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081
  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081
  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081
  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081
  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081
  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081
  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081  1.73205081
  1.72856642  1.71890633  1.69036204  1.61803399  1.41421356  1.41421356
  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.41343879  1.41250397  1.41228273  1.40954694  1.40346883  1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.
  1.          1.          1.          0.9989018   0.99756906  0.91501309
  0.83499962  0.61803399]
(572,)

In [59]:
VT.shape

(572, 572)

In [65]:
from sklearn.decomposition import TruncatedSVD

In [73]:
svd = TruncatedSVD(n_components=3)

In [74]:
svd.fit(cross_data1)

TruncatedSVD(algorithm='randomized', n_components=3, n_iter=5,
             random_state=None, tol=0.0)

In [75]:
print(svd.singular_values_)

[32.78113118 29.15782769 27.45783186]

In [76]:
df_svd = pd.DataFrame(svd.transform(cross_data1))
df_svd

                 0             1             2
0    -2.039629e-15  2.831360e-14  2.372653e-14
1     1.373080e-09 -7.870732e-10 -1.658321e-08
2     9.430646e-11 -7.829750e-10  1.272050e-09
3     4.074718e-14 -2.730921e-13  5.256289e-13
4     9.996209e-01 -8.908020e-03  2.548688e-04
...            ...           ...           ...
9305 -6.412245e-08  1.461448e-06  2.202864e-06
9306 -5.140922e-12 -4.366415e-12 -1.650472e-11
9307  3.887121e-08  3.686641e-06  1.932407e-06
9308  8.913359e-03  9.990705e-01 -4.169923e-02
9309  1.496562e-09 -1.769459e-08 -1.254275e-08

[9310 rows x 3 columns]

In [77]:
svd.explained_variance_ratio_

array([0.09096079, 0.07258435, 0.06545093])